apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdproject2-deployment
  labels:
    app: cicdproject2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicdproject2
  template:
    metadata:
      labels:
        app: cicdproject2
    spec:
      containers:
      - name: cicdproject2-container
        image: sreejeshd/cicdproject2:version1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
